# sphinx-apidoc -o ./docs/source ./spikingjelly
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import logging
import dataclasses
import inspect
import typing
import sys as _sys


class _DocsBuildLogFilter(logging.Filter):
    def filter(self, record):
        message = record.getMessage()
        ignored_prefixes = (
            "spikingjelly.activation_based.spike_op: try to use `torch.utils.cpp_extension.load_inline`",
            "If it is hanging, pleast try to delete torch_extensions cache directory.",
        )
        return not message.startswith(ignored_prefixes)


logging.getLogger().addFilter(_DocsBuildLogFilter())

# sys.path.insert(0, os.path.abspath('../../spikingjelly/'))
sys.path.insert(0, os.path.abspath("../../"))
print("sys.path", sys.path)
print("list dir", os.listdir(sys.path[0]))
# -- Project information -----------------------------------------------------

project = "spikingjelly"
copyright = "2020, PKU MLG, PCL"
author = "PKU MLG, PCL"

# The full version, including alpha/beta/rc tags
version = ""
release = ""

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
]
# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "navigation_depth": 4,
    "collapse_navigation": False,
    "show_nav_level": 1,
    "navbar_align": "right",
    "header_links_before_dropdown": 4,
    "navbar_center": ["navbar-nav"],
    "secondary_sidebar_items": ["page-toc", "sourcelink"],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/fangwei123456/spikingjelly",
            "icon": "fa-brands fa-github",
        },
    ],
    "logo": {
        "text": "SpikingJelly",
        "image_light": "_static/logo/sj-logo.png",
        "image_dark": "_static/logo/sj-logo.png",
    },
}


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "PyTorch": ("https://pytorch.org/docs/stable/", None),
}

show_authors = True

napoleon_use_ivar = True


def _resolve_postponed_signature_annotations(obj):
    try:
        signature = inspect.signature(obj)
        type_hints = typing.get_type_hints(obj, include_extras=True)
    except Exception:
        return None

    changed = False
    parameters = []
    for parameter in signature.parameters.values():
        annotation = type_hints.get(parameter.name, parameter.annotation)
        if annotation is not parameter.annotation:
            changed = True
            parameter = parameter.replace(annotation=annotation)
        parameters.append(parameter)

    return_annotation = type_hints.get("return", signature.return_annotation)
    if return_annotation is not signature.return_annotation:
        changed = True

    if not changed:
        return None

    return signature.replace(
        parameters=parameters,
        return_annotation=return_annotation,
    )


def _set_signature(obj, signature):
    try:
        obj.__signature__ = signature
    except Exception:
        pass


def _signature_without_bound_self(signature):
    parameters = list(signature.parameters.values())
    if parameters and parameters[0].name in {"self", "cls"}:
        parameters = parameters[1:]
    return signature.replace(
        parameters=parameters,
        return_annotation=inspect.Signature.empty,
    )


def _signature_without_annotations(signature):
    parameters = [
        parameter.replace(annotation=inspect.Parameter.empty)
        for parameter in signature.parameters.values()
    ]
    return signature.replace(
        parameters=parameters,
        return_annotation=inspect.Signature.empty,
    )


def _owner_class_for_method(method):
    qualname = getattr(method, "__qualname__", "")
    if "." not in qualname:
        return None
    owner_name = qualname.rsplit(".", 1)[0].split(".")[-1]
    module = _sys.modules.get(getattr(method, "__module__", ""))
    owner = getattr(module, owner_name, None) if module is not None else None
    return owner if inspect.isclass(owner) else None


def _class_from_fullname(name):
    module_name, _, class_name = name.rpartition(".")
    if not module_name:
        return None
    module = _sys.modules.get(module_name)
    if module is None:
        try:
            module = __import__(module_name, fromlist=[class_name])
        except Exception:
            return None
    owner = getattr(module, class_name, None)
    return owner if inspect.isclass(owner) else None


def _resolve_postponed_signature(app, obj, bound_method):
    if inspect.isclass(obj) and dataclasses.is_dataclass(obj):
        init_signature = _resolve_postponed_signature_annotations(obj.__init__)
        if init_signature is not None:
            _set_signature(obj.__init__, init_signature)
            _set_signature(obj, _signature_without_bound_self(init_signature))
        return None

    signature = _resolve_postponed_signature_annotations(obj)
    if signature is not None:
        _set_signature(obj, signature)
        owner = _owner_class_for_method(obj)
        if (
            owner is not None
            and dataclasses.is_dataclass(owner)
            and obj is owner.__init__
        ):
            _set_signature(owner, _signature_without_bound_self(signature))

    return None


def _resolve_postponed_type_hints(app, objtype, name, obj, options, args, retann):
    _resolve_postponed_signature(app, obj, False)

    cls = obj if inspect.isclass(obj) else _class_from_fullname(name)
    if objtype == "class" and cls is not None and dataclasses.is_dataclass(cls):
        signature = _resolve_postponed_signature_annotations(cls.__init__)
        if signature is not None:
            signature = _signature_without_bound_self(signature)
            signature = _signature_without_annotations(signature)
            return str(signature), None

    return None


def setup(app):
    app.connect(
        "autodoc-before-process-signature",
        _resolve_postponed_signature,
        priority=400,
    )
    app.connect(
        "autodoc-process-signature",
        _resolve_postponed_type_hints,
        priority=400,
    )


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["css/custom.css"]

html_favicon = "_static/logo/sj-logo.png"

autodoc_mock_imports = [
    "tensorboardX",
    "loris",
    "readline",
    "_C_gemm",
    "_C_neuron",
    "torchaudio",
    "onnx",
    "onnxruntime",
    "gym",
    "cloudpickle",
    "rarfile",
    "lava",
    "lyngor",
    "lynpy",
    "sklearn",
    "h5py",
    "triton",
    "cupy",
    "nir",
    "nirtorch",
    "lightning",
    "torchmetrics",
    "jsonargparse",
]
autoclass_content = "both"
autodoc_member_order = "bysource"
autodoc_inherit_docstrings = False
autodoc_typehints = "description"
autodoc_typehints_description_target = "all"
autodoc_typehints_format = "short"
python_use_unqualified_type_names = True
python_trailing_comma_in_multi_line_signatures = False
toc_object_entries_show_parents = "hide"

master_doc = "index"
