#!/usr/bin/env python3
"""Generate the Sphinx changelog page from CHANGELOG.md.

The converter intentionally supports only the small Markdown subset used by the
project changelog. Keeping the source format narrow makes the generated RST
stable and avoids adding a Markdown parser dependency to the docs build.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MARKDOWN_PATH = ROOT / "CHANGELOG.md"
RST_PATH = ROOT / "docs" / "source" / "changelog.rst"

HEADER = """.. This file is generated from CHANGELOG.md.
.. Do not edit this file directly. Run:
..   uv run python tools/generate_changelog_rst.py

"""

HEADING_CHARS = {
    1: "=",
    2: "-",
    3: "~",
    4: "^",
}


def append_blank(lines: list[str]) -> None:
    if lines and lines[-1] != "":
        lines.append("")


def display_width(text: str) -> int:
    return sum(2 if ord(char) > 127 else 1 for char in text)


def convert_inline(text: str) -> str:
    """Convert the inline Markdown forms used in CHANGELOG.md to RST."""

    text = re.sub(r"`([^`]+)`", r"``\1``", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"`\1 <\2>`__", text)
    return text


def convert_heading(line: str) -> list[str] | None:
    match = re.match(r"^(#{1,4})\s+(.+)$", line)
    if match is None:
        return None

    level = len(match.group(1))
    title = convert_inline(match.group(2).strip())
    underline = HEADING_CHARS[level] * display_width(title)
    return [title, underline]


def convert_markdown_to_rst(markdown: str) -> str:
    rst_lines: list[str] = [HEADER.rstrip(), ""]

    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()

        if line == "":
            append_blank(rst_lines)
            continue

        heading = convert_heading(line)
        if heading is not None:
            append_blank(rst_lines)
            rst_lines.extend(heading)
            rst_lines.append("")
            continue

        bullet_match = re.match(r"^(\s*)-\s+(.*)$", line)
        if bullet_match is not None:
            indent, body = bullet_match.groups()
            rst_lines.append(f"{indent}- {convert_inline(body)}")
            continue

        rst_lines.append(convert_inline(line))

    return "\n".join(rst_lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate docs/source/changelog.rst from CHANGELOG.md."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docs/source/changelog.rst is out of date.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    generated = convert_markdown_to_rst(MARKDOWN_PATH.read_text(encoding="utf-8"))

    if args.check:
        if not RST_PATH.exists():
            print(f"{RST_PATH} does not exist. Regenerate it.", file=sys.stderr)
            return 1
        current = RST_PATH.read_text(encoding="utf-8")
        if current != generated:
            print(
                f"{RST_PATH} is out of date. Run "
                "`uv run python tools/generate_changelog_rst.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    RST_PATH.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
