from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "publications.json"
RST_PATH = ROOT / "docs" / "source" / "publications.rst"

_URL_RE = re.compile(r"^https?://")


def _escape_rst_text(text: str) -> str:
    return text.replace("\\", "\\\\").replace("`", "``")


def _format_link(label: str, url: str) -> str:
    return f"`{_escape_rst_text(label)} <{url}>`__"


def _format_code_label(url: str, index: int, total: int) -> str:
    host = urlparse(url).netloc.lower()
    if host == "github.com":
        base = "GitHub"
    elif host == "gitlab.com":
        base = "GitLab"
    elif host == "openreview.net":
        base = "OpenReview"
    elif host == "anonymous.4open.science":
        base = "4Open"
    elif host == "doi.org":
        base = "DOI"
    else:
        base = host.removeprefix("www.") or "Link"

    return base if total == 1 else f"{base} {index}"


def _validate_entry(entry: Any, index: int) -> dict[str, Any]:
    if not isinstance(entry, dict):
        raise ValueError(f"Publication #{index} must be an object.")

    required_fields = ("title", "paper_url", "publisher", "code_urls")
    for field in required_fields:
        if field not in entry:
            raise ValueError(
                f"Publication #{index} is missing required field {field!r}."
            )

    title = entry["title"]
    paper_url = entry["paper_url"]
    publisher = entry["publisher"]
    code_urls = entry["code_urls"]

    if not isinstance(title, str) or not title.strip():
        raise ValueError(f"Publication #{index} has an invalid title.")
    if not isinstance(paper_url, str) or not _URL_RE.match(paper_url):
        raise ValueError(f"Publication #{index} has an invalid paper_url.")
    if not isinstance(publisher, str):
        raise ValueError(f"Publication #{index} has an invalid publisher.")
    if not isinstance(code_urls, list) or any(
        not isinstance(url, str) or not _URL_RE.match(url) for url in code_urls
    ):
        raise ValueError(f"Publication #{index} has invalid code_urls.")

    return {
        "title": title.strip(),
        "paper_url": paper_url.strip(),
        "publisher": publisher.strip(),
        "code_urls": [url.strip() for url in code_urls],
    }


def load_publications(data_path: Path = DATA_PATH) -> list[dict[str, Any]]:
    payload = json.loads(data_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or "publications" not in payload:
        raise ValueError(
            "publications.json must be an object with a 'publications' field."
        )

    publications = payload["publications"]
    if not isinstance(publications, list):
        raise ValueError("'publications' must be a list.")

    return [
        _validate_entry(entry, index) for index, entry in enumerate(publications, 1)
    ]


def build_rst(publications: list[dict[str, Any]]) -> str:
    lines = [
        ".. THIS FILE IS AUTO-GENERATED BY tools/generate_publications.py.",
        ".. DO NOT EDIT MANUALLY. EDIT publications.json AND RE-RUN THE GENERATOR.",
        "",
        "出版物 | Publications",
        "================================",
        "",
        "本页由 ``publications.json`` 自动生成，集中展示使用 SpikingJelly 的论文列表。",
        "",
        "This page is auto-generated from ``publications.json`` and lists publications",
        "that use SpikingJelly.",
        "",
        f"Total publications: {len(publications)}",
        "",
        ".. rubric:: Publication list",
        "",
    ]

    for publication in publications:
        title = _format_link(publication["title"], publication["paper_url"])
        publisher = _escape_rst_text(publication["publisher"])
        code_urls = publication["code_urls"]
        lines.append(f"#. {title}")
        if publisher or code_urls:
            lines.append("")
        if publisher:
            lines.append(f"   - Publisher: {publisher}")
        if code_urls:
            code_text = ", ".join(
                _format_link(
                    _format_code_label(url, code_index, len(code_urls)),
                    url,
                )
                for code_index, url in enumerate(code_urls, 1)
            )
            lines.append(f"   - Code: {code_text}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate docs/source/publications.rst from publications.json. "
            "Workflow: edit publications.json -> run this script -> commit both files."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with a non-zero code if the generated RST is out of date.",
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=DATA_PATH,
        help="Path to publications.json.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=RST_PATH,
        help="Path to the generated publications.rst file.",
    )
    args = parser.parse_args()

    publications = load_publications(args.data)
    rendered = build_rst(publications)

    if args.check:
        current = (
            args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        )
        if current != rendered:
            print(f"{args.output} is stale. Re-run tools/generate_publications.py.")
            return 1
        print(f"{args.output} is up to date.")
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
